/**
 * 
 */
package edu.ucdenver.ccp.common.string;

/**
 * Simple interface to promote object serialization and deserialization from a {@link String}
 * 
 * @author Center for Computational Pharmacology, UC Denver; ccpsupport@ucdenver.edu
 * @param <T>
 *            any type of object that might be stored and retrieved from a {@link String}
 * 
 */
public interface StringSerializable<T> {

	/**
	 * @return a {@link String} representation of the object
	 */
	public String serializeToString();

	// For every serializeToString() methods there should be an accompanying deserializeFromString()
	// method. This method is more suited to be a public static method however and therefore can't
	// be part of the interface.
	// /**
	// * @param input
	// * the {@link String} that will be parsed into values to use to initialize a new <T>
	// * @return an initialized object of type <T> generated by parsing the input {@link String}
	// * @throws IllegalArgumentException
	// * if the input {@link String} has an invalid format that cannot be deserialized
	// * into the expected object type <T>
	// */
	// public T deserializeFromString(String input) throws IllegalArgumentException;
}
